name: acdc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - PyQt5==5.15.4
    - opencv-python-headless==4.5.2.54
    - fvcore==0.1.5.post20210924
    - cloudpickle==2.0.0
    - omegaconf==2.1.1
    - torchvision==0.10.0
    - edt==2.1.2
    - ncolor==1.1.2
    - stardist==0.7.3
  - pyqtgraph
  - pandas
  - pytables
  - tqdm
  - natsort
  - scikit-image=0.18
  - pyglet
  - seaborn
  - numba
  - requests
  - tensorflow<2.6.0
  - pytorch=1.9
  - munkres
  - scikit-learn
  - jupyterlab
  - boto3
